// <auto-generated />
using Cloud1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cloud1.Migrations
{
    [DbContext(typeof(Cloud1Context))]
    partial class Cloud1ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            //modelBuilder.Entity("Cloud1.Models.CartItem", b =>
            //    {
            //        b.Property<int>("Id")
            //            .ValueGeneratedOnAdd()
            //            .HasColumnType("int");

            //        SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

            //        b.Property<int>("Amount")
            //            .HasColumnType("int");

            //        b.Property<int>("Cream1Id")
            //            .HasColumnType("int");

            //        b.Property<string>("ShoppingCartId")
            //            .HasColumnType("nvarchar(450)");

            //        b.Property<double>("TotalPrice")
            //            .HasColumnType("float");

            //        b.Property<int>("idShopCart")
            //            .HasColumnType("int");

            //        b.HasKey("Id");

            //        b.HasIndex("Cream1Id");

            //        b.HasIndex("ShoppingCartId");

            //        b.ToTable("CartItem");
            //    });

            modelBuilder.Entity("Cloud1.Models.IceCream", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<string>("IceDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("imageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IceCream");
                });

            modelBuilder.Entity("Cloud1.Models.IceCream1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("IceDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("imageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isAvailable")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("IceCream1");
                });

#pragma warning restore 612, 618
        }
    }
}
